version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sph_development
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  sph-server:
      build: .
      depends_on:
        - postgres
      restart: on-failure
      environment:
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_NAME=sph_development
        - DB_USER=postgres
        - DB_PASS=mysecretpassword
        - LOG_LEVEL=INFO
        - PORT=8080
        - ENV=development
      ports:
        - 8080:8080
      command: sh -c "sleep 10; ./sph-backend-coding-challenge migrate; ./sph-backend-coding-challenge start"

